<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(MSBuildThisFileDirectory)/../Webinex.Calendar.All/Package.props" />

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Webinex.Calendar.Abstractions\Webinex.Calendar.Abstractions.csproj" />
      <ProjectReference Include="..\Webinex.Calendar\Webinex.Calendar.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
    </ItemGroup>

</Project>
