<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(MSBuildThisFileDirectory)/../Webinex.Calendar.All/Package.props" />

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Webinex.Calendar</PackageId>
        <RootNamespace>Webinex.Calendar</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ical.Net" Version="5.2.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
        <PackageReference Include="NodaTime" Version="3.2.2" />
        <PackageReference Include="System.Linq.Async" Version="6.0.1" />
        <PackageReference Include="Webinex.Asky" Version="1.5.0" />
        <PackageReference Include="Webinex.Coded" Version="1.0.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Webinex.Calendar.Abstractions\Webinex.Calendar.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Remove="Webinex.Calendar.csproj.DotSettings" />
    </ItemGroup>

</Project>
